# Site settings
title: Your Project Title
repository: manabu-nakamura/jekyll-gfm-admonitions2
description: >-
  A description of your project

#markdown: GFM
#markdown: CommonMarkGhPages
#commonmark:
#  options: ["UNSAFE", "SMART", "FOOTNOTES"]
#  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
plugins:
#- jekyll-gfm-admonitions
- jekyll-optional-front-matter

exclude: 
  - "**/*.ts" # Exclude source code files!
  - "**/*.js"
  - "*.ts" # Also those in the root directory!
  - "*.js"
  - "*.json" # Don't forget about assets!
  - node_modules/ # And large vendored directories
  # And these ignore all the artifacts the build produces:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/